tf/configs/example.yaml, tf/train.py
Originally: https://github.com/glinscott/leela-chess/pull/688
=> Add support for properly pre-split test and train input data.

tf/configs/example.yaml, tf/tfprocess.py
Originally: https://github.com/glinscott/leela-chess/pull/681
=> Change how frequently test batches are run

tf/chunkparser.py, tf/tfprocess.py
Originally: https://github.com/glinscott/leela-chess/pull/691
=> Normalize 50 move rule plane in training

tf/tfprocess.py
Originally: https://github.com/glinscott/leela-chess/pull/690
=> Port training changes to enable batch normalization betas from leela-zero

scripts/upload.sh
This script monitors a directory and uploads files that are prefixed with e.g. `64x6`.
=> add upload script

scripts/split.sh
Copied off of the training machine as is currently being used for 'main' training.
Will need work to be compatible with the start.sh in development.
=> Add nousian's split monitoring script.

scripts/split.sh
=> simplify split.sh and respect windowsize

tf/start.sh
An untested suggestion to copy changed yaml file to a github branch every time training starts. If the yaml file is unchanged the git operation should not do anything.
=> Copy changed yaml file to github

tf/tfprocess.py
Closes #28, see the discussion there for rationale. I don't think a consensus on whether this can be merged into the current test run or whether a new one should be started has been reached yet.
=> Use ghost batch norm to match A0 paper

tf/train.py
untested, but it might make it work for windows.
=> Switch to standard TF checkpoint file parsing rather than hand rolled.

scripts/split.sh
=> Perform independent pruning of test and train to allow for rebalancing.

tf/update_steps.py
=> Step update script

tf/net_to_model.py, tf/update_steps.py, tf/upgrade.py
Untested, but should work. Addresses https://github.com/LeelaChessZero/lczero-training/pull/61#issuecomment-462096546
=> Pass correct number of placeholders to init_net

tf/tfprocess.py
Since I needed to add the adjustable clipping parameters, I made the whole thing optional.
=> Add renorm support.

tf/tfprocess.py
I think I'm not the only person who had a copy of this patch lying around - so lets just submit it...
=> Batch process weight loading for increased performance.

tf/tfprocess.py
Policy accuracy was quite wrong without this change.
=> Add policy accuracy function that corrects for masking.

tf/tfprocess.py, tf/train.py
Every validation_steps or total_steps the entire validation dataset is enumerated.  No shuffling no sampling.
Not currently sorted, so if validation dataset is not an exact multiple of split batch size there could be some run to run variance.
Only supports v4 data.
=> Add optional validation dataset

tf/chunkparser.py
About 10% speedup on input pipeline limited cases.
=> Remove unnecessary tobytes calls

tf/chunkparser.py
The current version can deadlock if a reader process dies and the pipe gets full. It shouldn't happen in normal operation but this is the only place I can think that could cause a deadlock. This commit checks if the chunk filename pipe is full and skips it in that case instead of blocking forever.
Works on Linux but needs testing on Windows before merging. @jjoshua2
About 1% slower than before on pipeline limited cases in my testing.
=> Don't block on full pipes

tf/chunkparser.py
Maybe this works on Windows? @jjoshua2 @leedavid
=> Queue for chunk filenames

tf/chunkparser.py, tf/train.py
=> V5 training data support

tf/chunkparser.py, tf/tfprocess.py, tf/train.py
Significant refactoring of experimental pipeline extractors to avoid nested tf.where based logic.
=> Add input type 3 support to training

tf/chunkparser.py, tf/net.py, tf/tfprocess.py, tf/train.py
=> Add support for input format 4 and 132

tf/train.py
Specifically support for.
1) Sorting chunks to select newest by a method other than mtime, for systems where mtime retrieval is slow.
2) Supporting multiple input directory specification in case its not possible to glob the directory names.
3) Flush the sort messages so they show up before sorting completes.
=> Add some extensions to chunk retrieval.

tf/chunkparser.py, tf/train.py
Implement V6 training format and a first version of value focus in training.
=> V6 training format and value focus

tf/configs/example.yaml, tf/tfprocess.py, tf/train.py
Also added the fix that seems to be necessary for my RTX cards as well
=> Turn off AutoSharding and apply memory growth for multi-gpu.

tf/tfprocess.py
I don't remember why we scale things like this exactly - but the actual batches the grad norm is calculated on are smaller with multiple gpus so we should treat them as such for the grad norm calculation adjustments.
=> Correct logic for grad norm for multigpu.

tf/tfprocess.py
Now that our minimum version is 2.4 ...
Some small cleanups while I am here:
1) Long overdue refactor to pull the train step with optional train reporting out into its own function like the test reporting.
I did this since I was going to have to indent the whole section for adding trace marker to improve the profiler experience otherwise...
2) I also took a couple of first time logics from process_v2 and made them unconditional in process_loop_v2. Also a validity check that doesn't need to get invoked every loop...
Trace does nothing if profiling is disabled - and logic to start/stop profiler is off by default.
=> Add support for profiling.

scripts/split.sh, tf/start.sh
Designed to make training more resilient to changes in contribution rate.
=> Some script updates from main training.

tf/tfprocess.py
test_dataset is being set to train
=> fixed bug/typo

tf/tfprocess.py
Before this change, each gpu clipped to its own norm - which could mean that its contribution to the total gradient got scaled unevenly.
This would then result in the applied gradient being in the wrong direction compared to both parts being scaled equally.
NOTE: This is a hack.  gradient_aggregator on Optimizer is not a documented public property.  It is especially undocumented that it contains the default aggregator value if None was passed at construction.  We need this default aggregator, because the 'documented' function to call to aggregate things crashes out with our grads as input. 
I suspect it might have something to do with None grads filtering that the default aggregator does (since None grads aren't variables, they don't have replica context attached to them or something and …
=> Correctly calculate gradient clipping on aggregate gradients in multi-gpu

tf/chunkparser.py, tf/train.py
Almost identical to code currently in use on all training runs - just made parameterizable.
=> Diff focus

tf/chunkparsefunc.py, tf/chunkparser.py, tf/experimental_parsing.py, tf/train.py
A bit ugly, but it appears to mean I can run high numbers of workers on windows without crashing the machine.
=> Refactor to avoid loading tensorflow into ChunkParser workers.
