- tf/configs/example.yaml
- tf/tfprocess.py
When doing a long bootstrap rather than an incremental train, checkpointing in the middle has significant value. So optionally add that ability back rather than only checkpointing at the end.
> Add ability to specify checkpoint step frequency.

- tf/tfprocess.py
- tf/train.py
If you resumed from part way through a total_steps count, it would still run for total_steps, which is definitely not ideal.
By moving the process_loop into tfprocess we can easily use the current step count to reduce the number of steps performed so the process will complete on a multiple of total_steps.
> Move process loop into tfprocess.py to better handle resume.

- tf/start.sh
This update adds the following features:
- utilize ramdisk
- train multiple networks on the same data
- permanent test/train split
It assumes that another script prepares the test/train split and that the underlying `train.py` script utilizes multigpu support in the future. Furthermore it assumes that yet another script will upload the correct network from `$NETDIR` to the server.
Please provide your feedback!
> initial new pipeline proposal

- tf/configs/example.yaml
- tf/tfprocess.py
While testing for the new lc0 training run I decided on 2500 steps as a desired value for total_steps.  But this isn't a multiple of 200, which leaves a bit of an odd train value reporting structure.
By adding this configuration I can change the train average reporting interval up to 250.  Also added a fail safe to ensure we always report the train at the end rather than lose the data if the configured value is not aligned with the total_steps.
> Replace 'NUM_STEPS_TRAIN' with a configurable value.

- scripts/split.sh
- tf/start.sh
Ok in hindsight I should've split into various commits, but this is what I implemented:
- allow continues when the `$TRAINDIR` and `$TESTDIR` exist
- implement exclusive lock on rsync from `start.sh` and file removal from `split.sh` through `flock`
- implement game file integrity by making sure that file size > 0 and file size is a multiple of 8276
> Add lock, allow split continuing, check file integrity

- tf/tfprocess.py
The TensorBoard histogram feature allows visualisation of how the distribution of weights in the network changes over the training process ([Guide](https://www.tensorflow.org/programmers_guide/tensorboard_histograms)). This gives us more information for network debugging, similar and hopefully better than skewness measures that people have used.
This PR saves the histogram summary of the network weights necessary for this. TensorBoard will then pick them up automatically and add a Histogram tab where the weight histograms can be seen. This PR also names the weights and biases so that they are grouped correctly in TensorBoard ([Example](https://i.stack.imgur.com/IttNH.jpg) of what it may look like.)
This is currently untested, but scs-ben has agreed to check if it works soon.
> Save TensorBoard histogram summary of weights

- tf/tfprocess.py
This extensive PR forces the current value for Learning Rate to be added to the TensorBoard logs.
This change can be added to an existing network with no additional work having to be done.
> track the LR

- tf/tfprocess.py
I often forget to remove this line when doing a cyclical LR scheme. Also, if people aren't putting their values in the correct order they aren't doing it right and shouldn't rely on this to fix it.
> remove lr value sorting

- scripts/pack.py
- scripts/unpack.py
Recompresses trainingdata into bz2 files, improves compression by a factor 2.3
Examples:
```
./pack.py -i trainingdata -o packed -n 1000
ls packed/*.bz2 | parallel ./unpack.py -i {} -o unpacked
```
> Transposedcompression

- tf/tfprocess.py
- tf/train.py
This PR allows training with larger batches than GPU memory can store at once. This is done by splitting a batch into many smaller batches, of which the gradients are accumulated to perform one gradient update. The implementation is adapted from [this StackOverflow answer](https://stackoverflow.com/questions/46772685/how-to-accumulate-gradients-in-tensorflow).
By default, no splitting of batches is performed. If `num_batch_splits` is added to the config yml under the training key, the batch is split into that many sub-batches which are then processed independently, accumulating gradients. This is very similar to training with the higher batch size in the first place, and it is *fully equivalent* if https://github.com/LeelaChessZero/lczero-training/pull/29 is merged.
As a result, this …
> Implement gradient accumulation

- tf/tfprocess.py
Currently, there are 6 similar copies of each variable in the histogram tab: e.g. `bn0/batch_normalization/beta_0`, `.../beta_0_1`, ..., `.../beta_0_5`. I believe that this is due to new histogram nodes being created every time calculate_test_summaries is called, which causes TensorBoard to try to rename them.
This PR changes it so that histogram nodes are only created once, thus TB should be able to reuse the summary nodes to make the histograms easier to view.
Again, I don't have things set-up properly to be able to test whether this actually works (but I think it should). Merging this PR shouldn't need a newly generated checkpoint unlike last time https://github.com/LeelaChessZero/lczero-training/pull/20.
> Fix duplicate histogram summaries for same variable

- tf/tfprocess.py
The previous implementation of Xavier init is completely wrong for conv layers, initialising values too large. This is likely the cause for the long time that a new net needs to be trained before the mse loss drops, and as sergiovieri points out, during this period the value head output is always 1. Also, notice how the moving variances for the first BN in every residual block in the current Tensorboard are close to 1 at the start of the net as they should be, but gradually move to over 100 as you get deeper into the network. This is a sign that the scale of the activations in the identity path in the ResNet is growing significantly throughout residual blocks.
This PR changes the init to be the correct Xavier initialisation for a Gaussian (as opposed to the original uniform distribution …
> Fix scale of weight initialization

- tf/tfprocess.py
See #42. This also puts the update ratios into a histogram/distribution so that it's easier to view them across the whole network. Running mean and running variance are excluded since they are independent of learning rate.
> Log update ratio of weights

- tf/tfprocess.py
- tf/train.py
This is a follow-up to https://github.com/LeelaChessZero/lczero-training/pull/38 with only the SWA parts pulled out and slightly refactored to be nicer. I took out the change to LR schedule for now as it isn't required for SWA (but the paper does say that it works well with cyclical learning rates).
A potential issue with Error's previous code was that swa_cycle (now renamed to swa_steps) -- how many steps between SWA updates there are -- was coupled with swa_max_n -- the maximum momentum term of the exponential moving average in the SWA. The SWA paper only updates the SWA weights at the end of each epoch (thousands or more steps) and has max_n at 40. Any suggestions for better names than swa_max_n, since it isn't a hard cut-off?
The original implementation was slow (less than half the …
> SWA, attempt 2

- tf/chunkparser.py
- tf/decode_training.py
- tf/shufflebuffer.py
- tf/tfprocess.py
- tf/train.py
See https://github.com/LeelaChessZero/lc0/pull/722.
This is backwards compatible to loading V3TrainingData by setting root_q, best_q, root_d, root_q to 0.0 and not masking away illegal moves. Setting q_ratio in the interval [0, 1] (default 0) allows adjustment of how much q is mixed into z. In training, this PR changes nothing by default.
I started a training run on CCRL with v3 data and it hasn't broken at 1000 steps yet.
> Support V4TrainingData

- tf/net.py
* Populate policyFormat and valueFormat fields in old protobufs
without these fields.
* Allow saving .pb.gz back to another .pb.gz,
useful if you add code to modify the pb weights.
* Print some more metadata about the protobuf file.
> net.py: Fix missing fields from network format

- tf/tfprocess.py
I don't think these really need to be optional, so I didn't bother adding options.
> Disable redundant gammas and add softmax feeding bias regularization.

- scripts/fixorder.py
- scripts/initsplit.py
- scripts/rescore.sh
- scripts/stage.sh
fixorder.py is useful when starting training for the first time and rescoring has messed with the timestamps on the files so they don't match the numerical order anymore.
initsplit.py is a super fast alternative to split.sh that works as a once off when setting up training for the first time.
rescore.sh runs rescorer in a loop - should take more parameters...
stage.sh watches file system events and moves files to a different directory (on the same file system) so that rescorer never tries to rescore a partially written file.
> Add some useful scripts

- tf/chunkparser.py
We've seen these values get corrupted, better to crash than use them incorrectly.
> Check best q and d values before potentially using them for training.

- tf/net.py
At the moment the code works because `pb.NetworkFormat.VALUE_CLASSICAL == pb.NetworkFormat.POLICY_CLASSICAL == 0`. But at some point this will change, and then it will break.
> Bug in policy format initialisation

- tf/tfprocess.py
Significantly reduces the log size.
Previously graphs were saved in all logs every time training was started or restored. This should decrease the log sizes especially on the training server which restarted the training often.
> Don't save graph in logs

- tf/net.py
- tf/tfprocess.py
- tf/train.py
TF 2.0 changes removed the run name from the saved weight file filename. This restores the old behaviour.
Also sneaked in a commit to make the number of workers configurable, with high core CPUs the default behaviour makes very many workers which uses a lot of memory.
> Save weights file with run name in the filename

- tf/tfprocess.py
I'm not certain this is actually identical to the pre v2 conversion, but definitely the old code was not specifying a number of buckets - so I am guessing the old code default buckets is the same number as the new code default buckets...
This should result in a 30 fold reduction in tensorboard logging size for the test steps - which should bring it closer in size to the train ones.
> Return to using default number of buckets for weight histogram

- tf/net.py
- tf/net_to_model.py
- tf/tfprocess.py
Removes the step where weights are stored in list and instead writes them directly to protobuf based on Tensorflow variable names. Fixes classical policy head support.
Tested successfully shortly training from scratch and `net_to_model` from existing network with and without renorm.
Also some other formatting fixes. Removing backslashes fixes some graph optimizer error messages. There was a tensorflow bug report about it, but I can't find it right now.
> Direct to protobuf save and replace

- scripts/shuffle.py
- tf/chunkparser.py
- tf/tfprocess.py
- tf/train.py
The current input data pipeline stores a copy of list of chunks for every reader process. Since by default there is only one game per chunk, with millions of chunks the list of filenames can take hundreds of MB of memory. When that is multiplied by number of reader processes it can take many GB.
This PR modifies the pipeline so that the list of files is stored only once and changes the multiprocessing start method from spawn to platform default (fork on Linux, spawn on Windows). fork start_method can reuse shared read only memory for each process further decreasing the memory consumption. I left it commented out for testing. There are some things that work differently with spawn and fork methods.
Script is included for shuffling and merging training data on disk. Using much larger chunks …
> Less memory intensive input pipeline

- tf/train.py
Not quite as random, but probably good enough and I'm pretty sure a bit faster.
SKIP_MULTIPLE is a trade off of quality/speed for ram usage.
Still not as good as chunkparser though - I can only manage 3050pos/sec. Seems to decide to only use about 50% cpu load for some reason. Chunkparser is easier on the cpu, only 30% load and it gets 4250pos/sec
Might do a bit more fine tuning.
> Faster way of doing experimental pipeline

- tf/tfprocess.py
Having the number of convolution channels divisible by 8 is faster with cudnn-fp16 and doesn't seem to really affect the prediction performance. 128x10 net with 8 channels gets max 93k nps on backendbench and 4 gets 87k.
> 8 channels in moves left 1x1 convolution

- tf/requirements.txt
Adding protobuf 3.12.1 to the list of requirements for lczero-training (if I understand what I'm doing)
> Needs protobuf in requirement.txt

- README.md
As per https://github.com/LeelaChessZero/lczero-training/issues/132, training data URL in README.md is outdated.
> README: Update training data URL

- tf/chunkparser.py
- tf/net.py
- tf/tfprocess.py
- tf/train.py
This is pretty trivial since the only difference to canonical hectoplies is in which history items are stored in the history planes. So can reuse the same extractors as for canonical hectoplies.
> Add support for canonical v2.

- tf/tfprocess.py
The grads were unused, so forcing autograph to try and setup everything to compute each individual mean across the replicas was pointless and very expensive.
Saves 80 seconds for first train step on RAF's training machine.
> Multigpu startup performance improvement

- tf/chunkparser.py
Also formatting.
A different fix for #75
Unlike ghotrix's version this doesn't require changing all functions on chunkparser to static.
> Fix weakref pickle issue.

- tf/tfprocess.py
Seems multi-gpu for some reason caches the result of the optimizer's LR requesting function across steps.  This means the first LR retrieved gets used for all future steps.
Changing active_lr to be a variable causes things to be processed correctly.
> Use a variable for active_lr to fix bug with multi-gpu

- tf/net.py
- tf/tfprocess.py
Requires the following added to NetworkFormat in net.proto
// Activation used everywhere except head outputs or otherwise specified.
enum DefaultActivation {
DEFAULT_ACTIVATION_RELU = 0;
DEFAULT_ACTIVATION_MISH = 1;
}
optional DefaultActivation default_activation = 7;
> Add support for mish activation for most cases of activation in network.
